export const categoryToSpeciality: Record<string, string[]> = {
  "General Symptoms": ["General Physician", "Internal Medicine"],
  "BP & Heart-related Issues": ["Cardiologist", "Endocrinologist"],
  "Diabetes, Thyroid & Hormonal Disorders": ["Endocrinologist"],
  "Bone, Joint & Muscle Problems": ["Orthopedic"],
  "Skin & Hair Issues": ["Dermatologist"],
  "Sexual Health": ["Sexologist"],
  "Pain, Injuries & Physical Ailments": ["Pain Specialist"],
  "Cough, Cold & Breathing Issues": ["Pulmonologist"],
  "Stomach & Digestion Issues": ["Gastroenterologist"],
  "Women’s Health": ["Gynaecologist"],
  "Children’s Health": ["Pediatrician"],
  "Ear, Nose & Throat Issues": ["ENT Specialist"],
  "Piles, Fissures & Fistula": ["Proctologist"],
  "Kidney & Urinary Issues": ["Nephrologist"],
  "Dental Issues": ["Dentist"],
  "Brain & Nerve Issues": ["Neurologist"],
  "Diet & Nutrition": ["Dietitian"],
};