export const products = [
  {
    "id": "5",
    "title": "Paracetamol 500mg",
    "seller_id": "1",
    "rating": "4.50",
    "mrp": 50.00,
    "image": "/images/paracetamol.jpg",
    "current_price": 30.00,
    "offers": "{10% Off}",
    "highlights": "{Relieves pain,Reduces fever}",
    "product_details": "Pain and fever relief",
    "manufacturer_details": "MediStore Labs",
    "marketer_details": "MediStore Pvt Ltd",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-12-31",
    "created_at": "2025-05-14 12:08:45.28872",
    "tags": "{Trending Now,Best Deals Now}"
  },
  {
    "id": "6",
    "title": "Amoxicillin 250mg",
    "seller_id": "2",
    "rating": "4.20",
    "mrp": 75.00,
    "image": "/images/amoxicillin.jpg",
    "current_price": 60.00,
    "offers": "{15% Off}",
    "highlights": "{Fights infection}",
    "product_details": "Used for bacterial infections",
    "manufacturer_details": "HealthCure Pharma",
    "marketer_details": "HealthCure Distributors",
    "country_of_origin": "India",
    "expires_on_or_after": "2025-09-30",
    "created_at": "2025-05-14 12:08:45.28872",
    "tags": "{Trending Now,Best Deals Now}"
  },
  {
    "id": "27",
    "title": "Glucon-D Instant Energy Drink",
    "seller_id": "1",
    "rating": "4.50",
    "mrp": 60.00,
    "image": "/images/glucon-d.jpg",
    "current_price": 52.00,
    "offers": "{10% off,Buy 2 Get 1 Free}",
    "highlights": "{Quick energy,Contains Vitamin D,Popular in summer}",
    "product_details": "Provides instant energy during summer or fatigue",
    "manufacturer_details": "Zydus Wellness Ltd.",
    "marketer_details": "Zydus Healthcare",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-01-01",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Trending Now,Best Deals Now}"
  },
  {
    "id": "28",
    "title": "Pampers Baby Dry Pants - M",
    "seller_id": "2",
    "rating": "4.80",
    "mrp": 399.00,
    "image": "/images/pampers.jpg",
    "current_price": 349.00,
    "offers": "{12% off}",
    "highlights": "{12-hour dryness,Stretchable waistband,Skin-friendly}",
    "product_details": "Comfortable baby diaper pants for medium size",
    "manufacturer_details": "Procter & Gamble",
    "marketer_details": "P&G Hygiene & Healthcare",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-06-30",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Baby Care,Deals of the day}"
  },
  {
    "id": "29",
    "title": "Dettol Antiseptic Liquid 500ml",
    "seller_id": "8",
    "rating": "4.70",
    "mrp": 150.00,
    "image": "/images/dettol.jpg",
    "current_price": 135.00,
    "offers": "{10% off}",
    "highlights": "{Trusted brand,Multipurpose use,Kills 99.9% germs}",
    "product_details": "Antiseptic disinfectant for first aid and cleaning",
    "manufacturer_details": "Reckitt Benckiser",
    "marketer_details": "RB Health India Pvt Ltd",
    "country_of_origin": "India",
    "expires_on_or_after": "2027-02-01",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Trending Now,Deals of the day}"
  },
  {
    "id": "30",
    "title": "ORS Electrolyte Sachets",
    "seller_id": "1",
    "rating": "4.30",
    "mrp": 25.00,
    "image": "/images/ors.jpg",
    "current_price": 22.00,
    "offers": "{}",
    "highlights": "{Quick hydration,WHO formula,Easy to mix}",
    "product_details": "Replenishes lost salts and fluids in dehydration",
    "manufacturer_details": "FDC Limited",
    "marketer_details": "FDC Ltd.",
    "country_of_origin": "India",
    "expires_on_or_after": "2025-11-01",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Best Deals Now}"
  },
  {
    "id": "31",
    "title": "Savlon Antiseptic Liquid 200ml",
    "seller_id": "2",
    "rating": "4.60",
    "mrp": 90.00,
    "image": "/images/savlon.jpg",
    "current_price": 81.00,
    "offers": "{10% off}",
    "highlights": "{Kills 99.99% germs,Mild on skin,Recommended by doctors}",
    "product_details": "For cuts, wounds, and first aid disinfection",
    "manufacturer_details": "ITC Ltd.",
    "marketer_details": "ITC Personal Care",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-04-01",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Trending Now}"
  },
  {
    "id": "32",
    "title": "Himalaya Baby Lotion 200ml",
    "seller_id": "2",
    "rating": "4.90",
    "mrp": 180.00,
    "image": "/images/himalaya-lotion.jpg",
    "current_price": 165.00,
    "offers": "{8% off}",
    "highlights": "{Gentle on skin,Natural ingredients,Paraben free}",
    "product_details": "Moisturizes and nourishes babys skin",
    "manufacturer_details": "The Himalaya Drug Company",
    "marketer_details": "Himalaya Wellness",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-10-01",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Baby Care,Ayurveda Care}"
  },
  {
    "id": "33",
    "title": "Colgate Strong Teeth Toothpaste 200g",
    "seller_id": "10",
    "rating": "4.50",
    "mrp": 105.00,
    "image": "/images/colgate.jpg",
    "current_price": 95.00,
    "offers": "{Free toothbrush}",
    "highlights": "{Strengthens enamel,Fresh breath,Clinically proven}",
    "product_details": "Daily fluoride toothpaste for strong teeth",
    "manufacturer_details": "Colgate Palmolive",
    "marketer_details": "Colgate-Palmolive India Ltd.",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-08-01",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Deals of the day}"
  },
  {
    "id": "34",
    "title": "Horlicks Health Drink 500g",
    "seller_id": "2",
    "rating": "4.40",
    "mrp": 230.00,
    "image": "/images/horlicks.jpg",
    "current_price": 210.00,
    "offers": "{8% off,Free 50g extra}",
    "highlights": "{Supports growth,Rich in calcium,Classic flavor}",
    "product_details": "Health drink for kids and adults with added nutrients",
    "manufacturer_details": "HUL",
    "marketer_details": "GSK Consumer Healthcare",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-09-30",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Trending Now,Best Deals Now}"
  },
  {
    "id": "35",
    "title": "Dabur Chyawanprash 1kg",
    "seller_id": "1",
    "rating": "4.60",
    "mrp": 350.00,
    "image": "/images/chyawanprash.jpg",
    "current_price": 310.00,
    "offers": "{11% off}",
    "highlights": "{Boosts immunity,Rich in Vitamin C,Traditional formula}",
    "product_details": "Ayurvedic health supplement to improve stamina and immunity",
    "manufacturer_details": "Dabur India Ltd.",
    "marketer_details": "Dabur",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-05-01",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Ayurveda Care,Trending Now}"
  },
  {
    "id": "36",
    "title": "Johnson's Baby Powder 200g",
    "seller_id": "2",
    "rating": "4.70",
    "mrp": 140.00,
    "image": "/images/johnsons-baby-powder.jpg",
    "current_price": 126.00,
    "offers": "{10% off}",
    "highlights": "{Mild fragrance,Clinically proven,Soft on baby skin}",
    "product_details": "Keeps babys skin dry and comfortable",
    "manufacturer_details": "Johnson & Johnson",
    "marketer_details": "Johnson & Johnson Pvt Ltd.",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-12-31",
    "created_at": "2025-05-17 10:00:00",
    "tags": "{Baby Care,Deals of the day}"
  },
  {
    "id": "37",
    "title": "Paracetamol 500mg Tablets - 10 Strip",
    "seller_id": "1",
    "rating": "4.50",
    "mrp": 25.00,
    "image": "paracetamol-500mg.png",
    "current_price": 20.00,
    "offers": "{10% off on 3 packs,Buy 2 Get 1 Free}",
    "highlights": "{Relieves mild to moderate pain,Reduces fever,Fast acting formula}",
    "product_details": "Paracetamol is a widely used over-the-counter medicine for pain relief and fever.",
    "manufacturer_details": "ABC Pharma Ltd., Mumbai",
    "marketer_details": "ABC Pharma Ltd.",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-05-17",
    "created_at": "2025-05-17 17:22:54.008824",
    "tags": "{Trending Now,Deals of the Day}"
  },
  {
    "id": "38",
    "title": "Ibuprofen 400mg Tablets - 10 Strip",
    "seller_id": "1",
    "rating": "4.20",
    "mrp": 30.00,
    "image": "ibuprofen-400mg.png",
    "current_price": 25.00,
    "offers": "{Flat \u20b95 off,Free delivery on 2 packs}",
    "highlights": "{Anti-inflammatory,Effective against pain and swelling,Recommended for muscle aches}",
    "product_details": "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used for relieving pain, swelling, and fever.",
    "manufacturer_details": "XYZ Labs Pvt. Ltd., Hyderabad",
    "marketer_details": "XYZ Labs Pvt. Ltd.",
    "country_of_origin": "India",
    "expires_on_or_after": "2027-05-17",
    "created_at": "2025-05-17 17:22:54.008824",
    "tags": "{Best Deals Now,Popular Combo Deals}"
  },
  {
    "id": "39",
    "title": "Cetirizine 10mg Tablets - 10 Strip",
    "seller_id": "1",
    "rating": "4.60",
    "mrp": 15.00,
    "image": "cetirizine-10mg.png",
    "current_price": 12.00,
    "offers": "{Extra 5% off,Combo offer available}",
    "highlights": "{Relieves allergy symptoms,Non-drowsy formula,Quick action}",
    "product_details": "Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, and sneezing.",
    "manufacturer_details": "HealthCure Labs, Pune",
    "marketer_details": "HealthCure Labs",
    "country_of_origin": "India",
    "expires_on_or_after": "2026-11-17",
    "created_at": "2025-05-17 17:22:54.008824",
    "tags": "{Trending Now,Ayurveda Care}"
  },
  {
    "id": "40",
    "title": "Dolo 650mg Tablets - 15 Strip",
    "seller_id": "1",
    "rating": "4.80",
    "mrp": 35.00,
    "image": "dolo-650.png",
    "current_price": 30.00,
    "offers": "{5% cashback on prepaid order,Free delivery}",
    "highlights": "{Effective for fever,Commonly prescribed,Safe for all ages}",
    "product_details": "Dolo 650 is used to treat fever and mild to moderate pain, especially in cases of cold and flu.",
    "manufacturer_details": "Micro Labs Ltd., Bengaluru",
    "marketer_details": "Micro Labs Ltd.",
    "country_of_origin": "India",
    "expires_on_or_after": "2027-01-17",
    "created_at": "2025-05-17 17:22:54.008824",
    "tags": "{Deals of the Day,Best Deals Now}"
  },
  {
    "id": "41",
    "title": "Ayurvedic Joint Pain Relief Oil - 100ml",
    "seller_id": "1",
    "rating": "4.10",
    "mrp": 120.00,
    "image": "ayurvedic-pain-oil.png",
    "current_price": 95.00,
    "offers": "{Save \u20b925,Ayurveda Combo Offer}",
    "highlights": "{Natural pain relief,Improves joint mobility,Herbal ingredients}",
    "product_details": "This Ayurvedic oil provides natural relief from joint and muscle pain using time-tested herbal formulations.",
    "manufacturer_details": "HerbalCure India Ltd., Haridwar",
    "marketer_details": "HerbalCure India Ltd.",
    "country_of_origin": "India",
    "expires_on_or_after": "2027-11-17",
    "created_at": "2025-05-17 17:22:54.008824",
    "tags": "{Ayurveda Care,Popular Combo Deals}"
  }
]
